"""`hills new`: create a hill from a template, init .vc, register it. No questions asked."""

import re
from pathlib import Path

from hills import paths, registry
from hills.errors import HillsError
from hills.hill import Hill
from hills.vc import VC

DEFAULT_TEMPLATE = "default"

GITIGNORE = """\
# Generated by hills. This excludes .hills/ from the surrounding project's git,
# the way uv excludes .venv/. Nothing outside this directory was touched.
#
# To track your hills in the project repo instead, replace the `*` below with
# these two lines, which must always stay excluded:
#   */.vc/
#   */private/
*
"""

HILL_GITIGNORE = """\
.vc/
.venv/
__pycache__/
"""


def template_paths() -> dict[str, Path]:
    """Templates ship inside the package; a source checkout also offers examples/."""
    roots = [Path(__file__).resolve().parent / "_templates"]
    source_examples = Path(__file__).resolve().parents[2] / "examples"
    if source_examples.is_dir():
        roots.append(source_examples)

    found: dict[str, Path] = {}
    for root in roots:
        if not root.is_dir():
            continue
        for entry in sorted(root.iterdir()):
            if entry.is_dir() and (entry / "hill.yaml").is_file():
                found.setdefault(entry.name, entry)
    return found


def available_templates() -> list[str]:
    return sorted(template_paths())


def _summary(readme: Path, width: int = 96) -> str:
    """The template README's first paragraph, as one line."""
    paragraph: list[str] = []
    for line in readme.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "<!--", "-->")):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    text = " ".join(paragraph)
    if len(text) <= width:
        return text
    return text[:width].rsplit(" ", 1)[0] + "…"


def template_summaries() -> list[tuple[str, str]]:
    """(name, one-line summary) for every example bundled with the tool."""
    return [
        (name, _summary(root / "README.md") if (root / "README.md").is_file() else "")
        for name, root in sorted(template_paths().items())
    ]


def _render(text: str, name: str) -> str:
    return text.replace("__NAME__", name)


def _rename(root: Path, name: str) -> None:
    """A hill's manifest name must match its directory, including for copied examples."""
    manifest = root / "hill.yaml"
    manifest.write_text(
        re.sub(r"^name:.*$", f"name: {name}", manifest.read_text(), count=1, flags=re.M)
    )
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        pyproject.write_text(
            re.sub(r'^name = ".*"$', f'name = "{name}"', pyproject.read_text(), count=1, flags=re.M)
        )


def _copy_template(template: str, dest: Path, name: str) -> None:
    source = template_paths().get(template)
    if source is None:
        known = "\n".join(f"  {name}  {summary}" for name, summary in template_summaries())
        raise HillsError(f"no example named {template!r}. Available:\n{known}")
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        target = dest / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        raw = path.read_bytes()
        try:
            target.write_text(_render(raw.decode(), name))
        except UnicodeDecodeError:
            target.write_bytes(raw)
        target.chmod(path.stat().st_mode)


def new(name: str, *, template: str = DEFAULT_TEMPLATE, where: Path | None = None) -> Hill:
    base = paths.project_root(where or Path.cwd()) / paths.HILLS_DIRNAME
    root = base / name
    if root.exists():
        raise HillsError(f"{root} already exists")

    base.mkdir(parents=True, exist_ok=True)
    gitignore = base / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE)

    _copy_template(template, root, name)
    _rename(root, name)
    (root / ".gitignore").write_text(HILL_GITIGNORE)
    (root / "private").mkdir(exist_ok=True)

    VC(root).init()
    hill = Hill.at(root)
    hill.refresh_exclude()
    registry.register(name, root)
    return hill
