"""`hills new`: create a hill from a template and init its version control. No questions asked."""

import re
import shutil
import subprocess
from pathlib import Path

from hills import manifest as manifest_mod, paths
from hills.errors import HillsError
from hills.hill import Hill
from hills.vc import VC

DEFAULT_TEMPLATE = "default"

GITIGNORE = """\
# Generated by hills. This excludes .autolab/ from the surrounding project's git,
# the way uv excludes .venv/. Nothing outside this directory was touched.
#
# To track your hills in the project repo instead, replace the `*` below with
# these two lines, which must always stay excluded:
#   hills/*/.vc/
#   hills/*/private/
*
"""

HILL_GITIGNORE = """\
.vc/
.venv/
__pycache__/
"""

# A modern (spec-4) hill is an ordinary git repo, so its own .gitignore is checked
# in. It must not exclude data/ or private/ (those are the LFS-tracked payload).
MODERN_HILL_GITIGNORE = """\
.venv/
__pycache__/
"""


def _ensure_git_lfs(root: Path) -> None:
    """Register git-LFS filters + hooks in this repo so `filter=lfs` paths are
    stored as pointers on commit. Spec-4 authoring requires the git-lfs binary."""
    if shutil.which("git-lfs") is None:
        raise HillsError(
            "git-lfs is not installed, but this hill stores its dataset with git-LFS.\n"
            "Install it (https://git-lfs.com) and re-run, e.g.:\n"
            "  # Debian/Ubuntu: sudo apt-get install git-lfs\n"
            "  # macOS:         brew install git-lfs"
        )
    subprocess.run(
        ["git", "-C", str(root), "lfs", "install", "--local"],
        capture_output=True,
        text=True,
        check=True,
    )


def template_paths() -> dict[str, Path]:
    """Templates ship inside the package; a source checkout also offers examples/."""
    roots = [Path(__file__).resolve().parent / "_templates"]
    source_examples = Path(__file__).resolve().parents[2] / "examples"
    if source_examples.is_dir():
        roots.append(source_examples)

    found: dict[str, Path] = {}
    for root in roots:
        if not root.is_dir():
            continue
        for entry in sorted(root.iterdir()):
            if entry.is_dir() and (entry / "hill.yaml").is_file():
                found.setdefault(entry.name, entry)
    return found


def available_templates() -> list[str]:
    return sorted(template_paths())


def _summary(readme: Path, width: int = 96) -> str:
    """The template README's first paragraph, as one line."""
    paragraph: list[str] = []
    for line in readme.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "<!--", "-->")):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    text = " ".join(paragraph)
    if len(text) <= width:
        return text
    return text[:width].rsplit(" ", 1)[0] + "…"


def template_summaries() -> list[tuple[str, str]]:
    """(name, one-line summary) for every example bundled with the tool."""
    return [
        (name, _summary(root / "README.md") if (root / "README.md").is_file() else "")
        for name, root in sorted(template_paths().items())
    ]


def _render(text: str, name: str) -> str:
    return text.replace("__NAME__", name)


def _rename(root: Path, name: str) -> None:
    """A hill's manifest name must match its directory, including for copied examples."""
    manifest = root / "hill.yaml"
    manifest.write_text(
        re.sub(r"^name:.*$", f"name: {name}", manifest.read_text(), count=1, flags=re.M)
    )
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        pyproject.write_text(
            re.sub(r'^name = ".*"$', f'name = "{name}"', pyproject.read_text(), count=1, flags=re.M)
        )


def _copy_template(template: str, dest: Path, name: str) -> None:
    source = template_paths().get(template)
    if source is None:
        known = "\n".join(f"  {name}  {summary}" for name, summary in template_summaries())
        raise HillsError(f"no example named {template!r}. Available:\n{known}")
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        target = dest / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        raw = path.read_bytes()
        try:
            target.write_text(_render(raw.decode(), name))
        except UnicodeDecodeError:
            target.write_bytes(raw)
        target.chmod(path.stat().st_mode)


def new(name: str, *, template: str = DEFAULT_TEMPLATE, where: Path | None = None) -> Hill:
    base = paths.project_hills(where or Path.cwd())
    root = base / name
    if root.exists():
        raise HillsError(f"{root} already exists")

    base.mkdir(parents=True, exist_ok=True)
    # One level above the hills, so the whole .autolab/ tree stays out of the
    # surrounding project's git.
    gitignore = base.parent / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE)

    _copy_template(template, root, name)
    _rename(root, name)
    (root / "private").mkdir(exist_ok=True)

    # The template's spec version chooses the layout: spec 4 is an ordinary git
    # repo with git-LFS; earlier specs use the legacy .vc + blob-lock mechanism.
    spec_version = manifest_mod.load(root / "hill.yaml").spec_version
    vc = VC(root)
    if spec_version >= manifest_mod.LFS_SPEC_VERSION:
        (root / ".gitignore").write_text(MODERN_HILL_GITIGNORE)
        vc.init_modern()
        _ensure_git_lfs(root)
        return Hill.at(root)

    (root / ".gitignore").write_text(HILL_GITIGNORE)
    vc.init()
    hill = Hill.at(root)
    hill.refresh_exclude()
    return hill
