"""Git, wrapped. A hill's git dir is `.vc`, so it never collides with the
project repo it lives inside. Users and agents never run git against a hill.
"""

import subprocess
import tarfile
import tempfile
from dataclasses import dataclass
from pathlib import Path

from hills.errors import HillsError

GIT_DIR_NAME = ".vc"

EXCLUDE_HEADER = "# Generated by hills at every version-control operation. Do not edit.\n"

# Never committed to a hill, independent of the manifest. Anchored entries are
# matched only at the hill root; the rest match at any depth.
ALWAYS_EXCLUDED_ANCHORED = (".vc/", "private/")
ALWAYS_EXCLUDED_ANYWHERE = (".venv/", "__pycache__/", ".pytest_cache/", ".DS_Store", "*.pyc")


def escape_pattern(path: str) -> str:
    """Quote a literal path so gitignore does not read it as a glob."""
    return "".join("\\" + ch if ch in "*?[]\\!# " else ch for ch in path)


@dataclass(frozen=True)
class TreeEntry:
    mode: str  # e.g. "100644", "100755", "120000" (symlink), "160000" (gitlink)
    otype: str  # "blob" | "commit" (gitlink)
    oid: str  # git object id
    path: str


class VC:
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        has_legacy = (self.root / GIT_DIR_NAME).is_dir()
        has_git = (self.root / ".git").exists()  # dir (normal) or file (linked worktree)
        if has_legacy and has_git:
            raise HillsError(
                f"{self.root} has both {GIT_DIR_NAME} and .git; refusing to guess which "
                "repository is the hill. Remove one."
            )
        # Legacy hills keep git in .vc; modern hills are ordinary git repos (.git).
        self.legacy = has_legacy and not has_git
        self.git_dir = self.root / (GIT_DIR_NAME if self.legacy else ".git")

    # -- plumbing ---------------------------------------------------------

    def _base(self) -> list[str]:
        if self.legacy:
            return ["git", f"--git-dir={self.git_dir}", f"--work-tree={self.root}"]
        return ["git", "-C", str(self.root)]

    def run(self, *args: str, check: bool = True) -> subprocess.CompletedProcess:
        result = subprocess.run(
            self._base() + list(args),
            cwd=self.root,
            capture_output=True,
            text=True,
        )
        if check and result.returncode != 0:
            raise HillsError(
                f"git {' '.join(args)} failed in {self.root}:\n{result.stderr.strip()}"
            )
        return result

    def out(self, *args: str) -> str:
        return self.run(*args).stdout.strip()

    # -- lifecycle --------------------------------------------------------

    @property
    def initialized(self) -> bool:
        return (self.root / GIT_DIR_NAME).is_dir() or (self.root / ".git").exists()

    def init(self) -> None:
        """Initialize a hill's version control (legacy .vc layout).

        A hill is addressed only through the tool, so its git dir lives in .vc and
        never collides with a surrounding project repo. Modern spec-4 (git-LFS) hills
        that are cloned by a node arrive as ordinary .git repos, which VC discovers
        automatically; :meth:`init_modern` creates that layout when authoring one.
        """
        subprocess.run(
            ["git", "init", "--quiet", f"--separate-git-dir={self.root / GIT_DIR_NAME}", str(self.root)],
            capture_output=True,
            text=True,
            check=True,
        )
        pointer = self.root / ".git"
        if pointer.exists():
            pointer.unlink()
        self.legacy = True
        self.git_dir = self.root / GIT_DIR_NAME
        self.run("config", "core.excludesFile", "")
        self.run("config", "commit.gpgsign", "false")

    def init_modern(self) -> None:
        """Initialize a MODERN hill as an ordinary git repo (.git), so `git clone`,
        `git lfs`, and everyday git work against it normally (spec-4 LFS hills)."""
        subprocess.run(
            ["git", "init", "--quiet", str(self.root)],
            capture_output=True,
            text=True,
            check=True,
        )
        self.legacy = False
        self.git_dir = self.root / ".git"
        self.run("config", "core.excludesFile", "")
        self.run("config", "commit.gpgsign", "false")

    def ensure_identity(self) -> None:
        """Hill commits are tool-made; fall back to a tool identity if git has none."""
        if not self.run("config", "user.email", check=False).stdout.strip():
            self.run("config", "user.email", "hills@localhost")
        if not self.run("config", "user.name", check=False).stdout.strip():
            self.run("config", "user.name", "hills")

    def write_exclude(self, extra_paths) -> None:
        """Rewrite .vc/info/exclude so lock-tracked content stays out of git."""
        info = self.git_dir / "info"
        info.mkdir(parents=True, exist_ok=True)
        lines = [EXCLUDE_HEADER]
        lines += [f"/{pattern}\n" for pattern in ALWAYS_EXCLUDED_ANCHORED]
        lines += [f"{pattern}\n" for pattern in ALWAYS_EXCLUDED_ANYWHERE]
        lines += [f"/{escape_pattern(path)}\n" for path in sorted(extra_paths)]
        (info / "exclude").write_text("".join(lines))

    # -- state ------------------------------------------------------------

    @property
    def has_commits(self) -> bool:
        return self.run("rev-parse", "--verify", "HEAD", check=False).returncode == 0

    def tree_hash(self) -> str:
        return self.out("rev-parse", "HEAD^{tree}")

    def commit_hash(self) -> str:
        return self.out("rev-parse", "HEAD")

    def status_porcelain(self) -> list[str]:
        return [line for line in self.out("status", "--porcelain").splitlines() if line]

    def is_dirty(self) -> bool:
        return bool(self.status_porcelain())

    def show(self, rev_path: str) -> str:
        return self.run("show", rev_path).stdout

    def ls_tree(self, rev: str = "HEAD") -> list[str]:
        return self.out("ls-tree", "-r", "--name-only", rev).splitlines()

    def log(self, limit: int) -> list[dict]:
        fmt = "%H%x1f%h%x1f%T%x1f%aI%x1f%s"
        raw = self.out("log", f"-{limit}", f"--pretty=format:{fmt}")
        entries = []
        for line in raw.splitlines():
            commit, short, tree, date, subject = line.split("\x1f")
            entries.append(
                {
                    "commit": commit,
                    "short": short,
                    "tree_hash": tree,
                    "date": date,
                    "message": subject,
                }
            )
        return entries

    # -- operations -------------------------------------------------------

    def commit(self, message: str, drop_from_index) -> str:
        self.ensure_identity()
        if drop_from_index:
            self.run(
                "rm", "-r", "--cached", "--quiet", "--ignore-unmatch", "--", *sorted(drop_from_index)
            )
        self.run("add", "-A")
        staged = self.run("diff", "--cached", "--quiet", check=False)
        if staged.returncode == 0 and self.has_commits:
            raise HillsError("nothing to commit: the hill matches its last committed version")
        self.run("commit", "--quiet", "-m", message)
        return self.tree_hash()

    def bundle_to(self, dest: Path) -> None:
        """Write a `git bundle` holding the full history reachable from HEAD."""
        self.run("bundle", "create", "--quiet", str(dest), "HEAD")

    def restore_from_bundle(self, bundle: Path) -> None:
        """Populate a freshly initialized .vc from a git bundle and check out its HEAD.

        The bundle records HEAD as a ref, so fetching it recreates the history
        exactly; the local branch is then pointed at that commit and checked
        out into the work tree.
        """
        self.run("bundle", "verify", "--quiet", str(bundle))
        self.run("fetch", "--quiet", str(bundle), "HEAD")
        self.run("reset", "--quiet", "--hard", "FETCH_HEAD")

    # -- pinned-revision raw export (0.12 authoritative materialization) ----

    def resolve_commit(self, rev: str = "HEAD") -> str:
        return self.out("rev-parse", "--verify", f"{rev}^{{commit}}")

    def tree_of(self, commit: str) -> str:
        return self.out("rev-parse", "--verify", f"{commit}^{{tree}}")

    def run_bytes(self, *args: str) -> bytes:
        """Run git capturing raw stdout bytes (for blob content)."""
        result = subprocess.run(self._base() + list(args), cwd=self.root, capture_output=True)
        if result.returncode != 0:
            raise HillsError(
                f"git {' '.join(args)} failed in {self.root}:\n"
                f"{result.stderr.decode('utf-8', 'replace').strip()}"
            )
        return result.stdout

    def tree_entries(self, commit: str) -> list[TreeEntry]:
        """Every path in the committed tree, recursively, with mode/type/oid."""
        raw = self.run_bytes("ls-tree", "-r", "-z", commit)
        entries: list[TreeEntry] = []
        for record in raw.split(b"\x00"):
            if not record:
                continue
            meta, _, path = record.partition(b"\t")
            mode, otype, oid = meta.decode().split()
            entries.append(TreeEntry(mode=mode, otype=otype, oid=oid, path=path.decode("utf-8")))
        return entries

    def blob_bytes(self, oid: str) -> bytes:
        """Raw bytes of a blob object (the committed content; a POINTER for LFS)."""
        return self.run_bytes("cat-file", "blob", oid)

    def attr_filter(self, commit: str, paths: list[str]) -> dict[str, str]:
        """The committed ``filter`` gitattribute per path (e.g. "lfs"), read from the
        tree at ``commit`` (not the working tree/index), so classification matches the
        exact version being scored. Absent -> "" (git reports "unspecified")."""
        if not paths:
            return {}
        stdin = ("\0".join(paths) + "\0").encode()
        result = subprocess.run(
            self._base() + ["check-attr", "--source", commit, "-z", "filter", "--stdin"],
            cwd=self.root,
            input=stdin,
            capture_output=True,
        )
        if result.returncode != 0:
            raise HillsError(
                "git check-attr --source failed (needs git >= 2.40):\n"
                + result.stderr.decode("utf-8", "replace").strip()
            )
        fields = result.stdout.split(b"\x00")
        out: dict[str, str] = {}
        # Output repeats: <path>\0 filter \0 <value>\0
        for i in range(0, len(fields) - 2, 3):
            path = fields[i].decode("utf-8")
            value = fields[i + 2].decode("utf-8")
            out[path] = "" if value in ("unspecified", "unset") else value
        return out

    def archive_to(self, dest: Path) -> None:
        """Extract the committed tree at HEAD into dest (LEGACY only)."""
        dest.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(suffix=".tar", delete=False) as handle:
            archive = Path(handle.name)
        self.run("archive", "--format=tar", "-o", str(archive), "HEAD")
        with tarfile.open(archive) as tar:
            tar.extractall(dest, filter="data")
        archive.unlink()
