"""Git, wrapped. A hill's git dir is `.vc`, so it never collides with the
project repo it lives inside. Users and agents never run git against a hill.
"""

import subprocess
import tarfile
import tempfile
from pathlib import Path

from hills.errors import HillsError

GIT_DIR_NAME = ".vc"

EXCLUDE_HEADER = "# Generated by hills at every version-control operation. Do not edit.\n"

# Never committed to a hill, independent of the manifest. Anchored entries are
# matched only at the hill root; the rest match at any depth.
ALWAYS_EXCLUDED_ANCHORED = (".vc/", "private/")
ALWAYS_EXCLUDED_ANYWHERE = (".venv/", "__pycache__/", ".pytest_cache/", ".DS_Store", "*.pyc")


def escape_pattern(path: str) -> str:
    """Quote a literal path so gitignore does not read it as a glob."""
    return "".join("\\" + ch if ch in "*?[]\\!# " else ch for ch in path)


class VC:
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        self.git_dir = self.root / GIT_DIR_NAME

    # -- plumbing ---------------------------------------------------------

    def _base(self) -> list[str]:
        return ["git", f"--git-dir={self.git_dir}", f"--work-tree={self.root}"]

    def run(self, *args: str, check: bool = True) -> subprocess.CompletedProcess:
        result = subprocess.run(
            self._base() + list(args),
            cwd=self.root,
            capture_output=True,
            text=True,
        )
        if check and result.returncode != 0:
            raise HillsError(
                f"git {' '.join(args)} failed in {self.root}:\n{result.stderr.strip()}"
            )
        return result

    def out(self, *args: str) -> str:
        return self.run(*args).stdout.strip()

    # -- lifecycle --------------------------------------------------------

    @property
    def initialized(self) -> bool:
        return self.git_dir.is_dir()

    def init(self) -> None:
        subprocess.run(
            ["git", "init", "--quiet", f"--separate-git-dir={self.git_dir}", str(self.root)],
            capture_output=True,
            text=True,
            check=True,
        )
        # `git init --separate-git-dir` leaves a .git file pointing at .vc.
        # A hill is addressed only through the tool, so drop the pointer and
        # keep .vc as the sole entry point.
        pointer = self.root / ".git"
        if pointer.exists():
            pointer.unlink()
        self.run("config", "core.excludesFile", "")
        self.run("config", "commit.gpgsign", "false")

    def ensure_identity(self) -> None:
        """Hill commits are tool-made; fall back to a tool identity if git has none."""
        if not self.run("config", "user.email", check=False).stdout.strip():
            self.run("config", "user.email", "hills@localhost")
        if not self.run("config", "user.name", check=False).stdout.strip():
            self.run("config", "user.name", "hills")

    def write_exclude(self, extra_paths) -> None:
        """Rewrite .vc/info/exclude so lock-tracked content stays out of git."""
        info = self.git_dir / "info"
        info.mkdir(parents=True, exist_ok=True)
        lines = [EXCLUDE_HEADER]
        lines += [f"/{pattern}\n" for pattern in ALWAYS_EXCLUDED_ANCHORED]
        lines += [f"{pattern}\n" for pattern in ALWAYS_EXCLUDED_ANYWHERE]
        lines += [f"/{escape_pattern(path)}\n" for path in sorted(extra_paths)]
        (info / "exclude").write_text("".join(lines))

    # -- state ------------------------------------------------------------

    @property
    def has_commits(self) -> bool:
        return self.run("rev-parse", "--verify", "HEAD", check=False).returncode == 0

    def tree_hash(self) -> str:
        return self.out("rev-parse", "HEAD^{tree}")

    def commit_hash(self) -> str:
        return self.out("rev-parse", "HEAD")

    def status_porcelain(self) -> list[str]:
        return [line for line in self.out("status", "--porcelain").splitlines() if line]

    def is_dirty(self) -> bool:
        return bool(self.status_porcelain())

    def show(self, rev_path: str) -> str:
        return self.run("show", rev_path).stdout

    def ls_tree(self, rev: str = "HEAD") -> list[str]:
        return self.out("ls-tree", "-r", "--name-only", rev).splitlines()

    def log(self, limit: int) -> list[dict]:
        fmt = "%H%x1f%h%x1f%T%x1f%aI%x1f%s"
        raw = self.out("log", f"-{limit}", f"--pretty=format:{fmt}")
        entries = []
        for line in raw.splitlines():
            commit, short, tree, date, subject = line.split("\x1f")
            entries.append(
                {
                    "commit": commit,
                    "short": short,
                    "tree_hash": tree,
                    "date": date,
                    "message": subject,
                }
            )
        return entries

    # -- operations -------------------------------------------------------

    def commit(self, message: str, drop_from_index) -> str:
        self.ensure_identity()
        if drop_from_index:
            self.run(
                "rm", "-r", "--cached", "--quiet", "--ignore-unmatch", "--", *sorted(drop_from_index)
            )
        self.run("add", "-A")
        staged = self.run("diff", "--cached", "--quiet", check=False)
        if staged.returncode == 0 and self.has_commits:
            raise HillsError("nothing to commit: the hill matches its last committed version")
        self.run("commit", "--quiet", "-m", message)
        return self.tree_hash()

    def archive_to(self, dest: Path) -> None:
        """Extract the committed tree at HEAD into dest."""
        dest.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(suffix=".tar", delete=False) as handle:
            archive = Path(handle.name)
        self.run("archive", "--format=tar", "-o", str(archive), "HEAD")
        with tarfile.open(archive) as tar:
            tar.extractall(dest, filter="data")
        archive.unlink()
